version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:14
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: nikolaygerasimov/foodgram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media/
    depends_on:
      - db
  frontend:
    env_file: .env
    image: nikolaygerasimov/foodgram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
  gateway:
    image: nikolaygerasimov/foodgram_gateway
    volumes:
      - static:/static/
      - media:/media/
    ports:
      - 8000:80