# Generated by Django 4.2.15 on 2024-08-14 19:12
import json
import os

from django.db import migrations

from foodgram.settings import BASE_DIR
from recipes.models import Ingredient


def set_data(param1, param2):
    with open(os.path.join(BASE_DIR, 'ingredients.json')) as file:
        data = json.load(file)
        ingredient_list = []
        for ingredient in data:
            ingredient_list.append(
                Ingredient(
                    name=ingredient['name'],
                    measurement_unit=ingredient['measurement_unit']
                )
            )

        Ingredient.objects.bulk_create(ingredient_list)


class Migration(migrations.Migration):
    dependencies = [
        ('recipes', '0004_alter_ingredientinrecipe_ingredient_and_more'),
    ]

    operations = [
        migrations.RunPython(set_data)
    ]